# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: [ push, pull_request, workflow_dispatch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          export
          git show-ref
          git clone -b git_envs https://github.com/aiharos/github-actions.git
          cd github-actions/check-commit; go run check.go "../../."
